export const LANGUAGE_OPTIONS = [
  { value: 'null', label: '自動検出' },
  { value: 'javascript', label: 'JavaScript' },
  { value: 'typescript', label: 'TypeScript' },
  { value: 'jsx', label: 'JSX' },
  { value: 'tsx', label: 'TSX' },
  { value: 'html', label: 'HTML' },
  { value: 'css', label: 'CSS' },
  { value: 'scss', label: 'SCSS' },
  { value: 'sass', label: 'Sass' },
  { value: 'less', label: 'Less' },
  { value: 'vue', label: 'Vue' },
  { value: 'svelte', label: 'Svelte' },
  { value: 'python', label: 'Python' },
  { value: 'java', label: 'Java' },
  { value: 'go', label: 'Go' },
  { value: 'rust', label: 'Rust' },
  { value: 'ruby', label: 'Ruby' },
  { value: 'php', label: 'PHP' },
  { value: 'csharp', label: 'C#' },
  { value: 'cpp', label: 'C++' },
  { value: 'c', label: 'C' },
  { value: 'kotlin', label: 'Kotlin' },
  { value: 'swift', label: 'Swift' },
  { value: 'dart', label: 'Dart' },
  { value: 'elixir', label: 'Elixir' },
  { value: 'bash', label: 'Bash' },
  { value: 'sh', label: 'Shell' },
  { value: 'zsh', label: 'Zsh' },
  { value: 'powershell', label: 'PowerShell' },
  { value: 'json', label: 'JSON' },
  { value: 'yaml', label: 'YAML' },
  { value: 'toml', label: 'TOML' },
  { value: 'xml', label: 'XML' },
  { value: 'ini', label: 'INI' },
  { value: 'graphql', label: 'GraphQL' },
  { value: 'sql', label: 'SQL' },
  { value: 'markdown', label: 'Markdown' },
  { value: 'dockerfile', label: 'Dockerfile' },
  { value: 'nginx', label: 'Nginx' },
] as const satisfies readonly Record<string, string>[]

export const LANGUAGE_NORMALIZATION = {
  js: 'javascript',
  ts: 'typescript',
  py: 'python',
  rb: 'ruby',
  rs: 'rust',
  kt: 'kotlin',
  ex: 'elixir',
  cs: 'csharp',
  ps1: 'powershell',
  yml: 'yaml',
  gql: 'graphql',
  md: 'markdown',
} as const satisfies Record<string, string>

export const LANGUAGE_DENORMALIZATION = Object.entries(LANGUAGE_NORMALIZATION).reduce(
  (acc, [short, full]) => {
    acc[short] = full
    acc[full] = full
    return acc
  },
  {} as Record<string, string>,
)

export const LANGUAGE_TO_EXTENSION = {
  javascript: '.js',
  js: '.js',
  typescript: '.ts',
  ts: '.ts',
  jsx: '.jsx',
  tsx: '.tsx',
  html: '.html',
  css: '.css',
  scss: '.scss',
  sass: '.sass',
  less: '.less',
  vue: '.vue',
  svelte: '.svelte',
  python: '.py',
  py: '.py',
  java: '.java',
  go: '.go',
  rust: '.rs',
  rs: '.rs',
  ruby: '.rb',
  rb: '.rb',
  php: '.php',
  csharp: '.cs',
  cs: '.cs',
  cpp: '.cpp',
  'c++': '.cpp',
  c: '.c',
  kotlin: '.kt',
  kt: '.kt',
  swift: '.swift',
  dart: '.dart',
  elixir: '.ex',
  ex: '.ex',
  bash: '.sh',
  sh: '.sh',
  zsh: '.zsh',
  powershell: '.ps1',
  ps1: '.ps1',
  json: '.json',
  yaml: '.yml',
  yml: '.yml',
  toml: '.toml',
  xml: '.xml',
  ini: '.ini',
  graphql: '.graphql',
  gql: '.graphql',
  sql: '.sql',
  markdown: '.md',
  md: '.md',
  nginx: '.conf',
  dockerfile: '',
} as const satisfies Record<string, string>

export const TEXTBLOCK_TYPE_INPUT_RULES_FIND_REGEX = /^```([a-z0-9]+)?(?::([^\s]+))?[\s\n]$/
export const CODEBLOCK_REGEX = /^```([a-z0-9]+)?(?::([^\n]+))?\n([\s\S]*?)\n```$/m

export const COLOR_SWATCHES = [
  '#000000',
  '#868e96',
  '#fa5252',
  '#e64980',
  '#be4bdb',
  '#7950f2',
  '#4c6ef5',
  '#228be6',
  '#15aabf',
  '#12b886',
  '#40c057',
  '#82c91e',
  '#fab005',
  '#fd7e14',
] as const satisfies readonly string[]
