name: CI

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Type check
        run: bun tsc

      - name: Lint and format check
        run: bun check

      - name: Build
        run: bun run build
        env:
          VITE_TURSO_CONNECTION_URL: ${{ secrets.VITE_TURSO_CONNECTION_URL }}
          VITE_TURSO_AUTH_TOKEN: ${{ secrets.VITE_TURSO_AUTH_TOKEN }}
          VITE_BETTER_AUTH_URL: ${{ secrets.VITE_BETTER_AUTH_URL }}
          VITE_BETTER_AUTH_SECRET: ${{ secrets.VITE_BETTER_AUTH_SECRET }}
          VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}
          VITE_GITHUB_CLIENT_SECRET: ${{ secrets.VITE_GITHUB_CLIENT_SECRET }}
          VITE_PASSKEY_RP_ID: ${{ secrets.VITE_PASSKEY_RP_ID }}
          VITE_PASSKEY_RP_NAME: ${{ secrets.VITE_PASSKEY_RP_NAME }}
          VITE_POLAR_ACCESS_TOKEN: ${{ secrets.VITE_POLAR_ACCESS_TOKEN }}
          VITE_POLAR_SERVER: ${{ secrets.VITE_POLAR_SERVER }}
          VITE_POLAR_WEBHOOK_SECRET: ${{ secrets.VITE_POLAR_WEBHOOK_SECRET }}
          VITE_POLAR_PRODUCT_ID: ${{ secrets.VITE_POLAR_PRODUCT_ID }}

      - name: Deploy to Cloudflare Workers
        run: bun run cf:build
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          VITE_TURSO_CONNECTION_URL: ${{ secrets.VITE_TURSO_CONNECTION_URL }}
          VITE_TURSO_AUTH_TOKEN: ${{ secrets.VITE_TURSO_AUTH_TOKEN }}
          VITE_BETTER_AUTH_URL: ${{ secrets.VITE_BETTER_AUTH_URL }}
          VITE_BETTER_AUTH_SECRET: ${{ secrets.VITE_BETTER_AUTH_SECRET }}
          VITE_GITHUB_CLIENT_ID: ${{ secrets.VITE_GITHUB_CLIENT_ID }}
          VITE_GITHUB_CLIENT_SECRET: ${{ secrets.VITE_GITHUB_CLIENT_SECRET }}
          VITE_PASSKEY_RP_ID: ${{ secrets.VITE_PASSKEY_RP_ID }}
          VITE_PASSKEY_RP_NAME: ${{ secrets.VITE_PASSKEY_RP_NAME }}
          VITE_POLAR_ACCESS_TOKEN: ${{ secrets.VITE_POLAR_ACCESS_TOKEN }}
          VITE_POLAR_SERVER: ${{ secrets.VITE_POLAR_SERVER }}
          VITE_POLAR_WEBHOOK_SECRET: ${{ secrets.VITE_POLAR_WEBHOOK_SECRET }}
          VITE_POLAR_PRODUCT_ID: ${{ secrets.VITE_POLAR_PRODUCT_ID }}
